// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4SnHRhR1QRgbJq0wsUgHm5EcsT4QTXig',
    appId: '1:173049571389:web:a4727eb8d543432ba1a254',
    messagingSenderId: '173049571389',
    projectId: 'we-chat-3bcee',
    authDomain: 'we-chat-3bcee.firebaseapp.com',
    storageBucket: 'we-chat-3bcee.appspot.com',
    measurementId: 'G-2QBEESZSR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJlSbS61X0XZHDNeYz-u3rxOEPn8sMvrA',
    appId: '1:173049571389:android:879f2d73b01a398ba1a254',
    messagingSenderId: '173049571389',
    projectId: 'we-chat-3bcee',
    storageBucket: 'we-chat-3bcee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-C_DOnxYuwrhgUAhVB_Nr0nd6dCYBin0',
    appId: '1:173049571389:ios:a36808c02e996ad7a1a254',
    messagingSenderId: '173049571389',
    projectId: 'we-chat-3bcee',
    storageBucket: 'we-chat-3bcee.appspot.com',
    androidClientId: '173049571389-0u94c9jrlpjjm918j3sdmbclti594aii.apps.googleusercontent.com',
    iosClientId: '173049571389-b86cavtfl6vp9eebncrb1uuv1htub22c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-C_DOnxYuwrhgUAhVB_Nr0nd6dCYBin0',
    appId: '1:173049571389:ios:a36808c02e996ad7a1a254',
    messagingSenderId: '173049571389',
    projectId: 'we-chat-3bcee',
    storageBucket: 'we-chat-3bcee.appspot.com',
    androidClientId: '173049571389-0u94c9jrlpjjm918j3sdmbclti594aii.apps.googleusercontent.com',
    iosClientId: '173049571389-b86cavtfl6vp9eebncrb1uuv1htub22c.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
